window.CATEGORY_BANK = [
  {
    "id": "oscar-winning-actors",
    "title": "Oscar-Winning Actors",
    "items": [
      "Daniel Day-Lewis",
      "Meryl Streep",
      "Tom Hanks",
      "Denzel Washington",
      "Cate Blanchett",
      "Leonardo DiCaprio",
      "Viola Davis",
      "Brie Larson",
      "Matthew McConaughey",
      "Julianne Moore",
      "Hilary Swank",
      "Emma Stone",
      "Jamie Foxx",
      "Reese Witherspoon",
      "Marion Cotillard",
      "Colin Firth",
      "Jeff Bridges",
      "Jennifer Lawrence",
      "Mahershala Ali",
      "Nicole Kidman",
      "Joaquin Phoenix",
      "Olivia Colman",
      "Frances McDormand",
      "Adrien Brody",
      "Helen Mirren",
      "Forest Whitaker",
      "Kate Winslet",
      "Sandra Bullock",
      "Natalie Portman",
      "Jean Dujardin",
      "Jennifer Hudson",
      "Anne Hathaway",
      "Eddie Redmayne",
      "Patricia Arquette",
      "Alicia Vikander",
      "Casey Affleck",
      "Allison Janney",
      "Rami Malek",
      "Laura Dern",
      "Brad Pitt",
      "Renee Zellweger",
      "Youn Yuh-jung",
      "Jessica Chastain",
      "Ke Huy Quan",
      "Da'Vine Joy Randolph"
    ]
  },
  {
    "id": "pop-stars",
    "title": "Pop Stars",
    "items": [
      "Taylor Swift",
      "Dua Lipa",
      "Ariana Grande",
      "Olivia Rodrigo",
      "Lady Gaga",
      "Madonna",
      "Britney Spears",
      "Katy Perry",
      "Miley Cyrus",
      "Sabrina Carpenter",
      "Billie Eilish",
      "Selena Gomez",
      "Justin Bieber",
      "Shawn Mendes",
      "Harry Styles",
      "The Weeknd",
      "Bruno Mars",
      "Rihanna",
      "Beyonce",
      "Adele",
      "Ed Sheeran",
      "Troye Sivan",
      "Charli XCX",
      "Kesha",
      "Lorde",
      "Camila Cabello",
      "Shakira",
      "Nelly Furtado",
      "Christina Aguilera",
      "Demi Lovato",
      "Pink",
      "Kelly Clarkson",
      "Avril Lavigne",
      "Carly Rae Jepsen",
      "Tate McRae",
      "Halsey",
      "Sia",
      "Doja Cat",
      "Jennifer Lopez",
      "Meghan Trainor",
      "Cyndi Lauper",
      "George Michael",
      "Robyn",
      "Paula Abdul",
      "Ellie Goulding"
    ]
  },
  {
    "id": "r-b-singers",
    "title": "R&B Singers",
    "items": [
      "Aaliyah",
      "Alicia Keys",
      "Ashanti",
      "Babyface",
      "Brandy",
      "Chris Brown",
      "Ciara",
      "D'Angelo",
      "Destiny's Child",
      "Erykah Badu",
      "Fantasia",
      "Ginuwine",
      "H.E.R.",
      "Janelle Monáe",
      "John Legend",
      "Khalid",
      "Lauryn Hill",
      "Luther Vandross",
      "Mario",
      "Mary J. Blige",
      "Maxwell",
      "Miguel",
      "Monica",
      "Musiq Soulchild",
      "Ne-Yo",
      "Omarion",
      "R. Kelly",
      "Rihanna",
      "Robin Thicke",
      "Sade",
      "Sam Cooke",
      "SZA",
      "Summer Walker",
      "TLC",
      "Tamar Braxton",
      "Toni Braxton",
      "Trey Songz",
      "Tyrese",
      "Usher",
      "Whitney Houston",
      "The-Dream",
      "Keith Sweat",
      "Anita Baker",
      "Jagged Edge",
      "Silk"
    ]
  },
  {
    "id": "grey-s-anatomy-characters",
    "title": "Grey'S Anatomy Characters",
    "items": [
      "Meredith Grey",
      "Cristina Yang",
      "Alex Karev",
      "George O'Malley",
      "Izzie Stevens",
      "Miranda Bailey",
      "Derek Shepherd",
      "Richard Webber",
      "Callie Torres",
      "Arizona Robbins",
      "Mark Sloan",
      "Lexie Grey",
      "Owen Hunt",
      "April Kepner",
      "Jackson Avery",
      "Amelia Shepherd",
      "Maggie Pierce",
      "Jo Wilson",
      "Andrew DeLuca",
      "Teddy Altman",
      "Tom Koracick",
      "Preston Burke",
      "Addison Montgomery",
      "Ben Warren",
      "Levi Schmitt",
      "Link",
      "Winston Ndugu",
      "Nick Marsh",
      "Catherine Fox",
      "Megan Hunt",
      "Carina DeLuca",
      "Nico Kim",
      "Taryn Helm",
      "Atticus Lincoln",
      "Stephanie Edwards",
      "Shane Ross",
      "Erica Hahn",
      "Denny Duquette",
      "Finn Dandridge",
      "Lucy Fields",
      "Heather Brooks",
      "Sadie Harris",
      "Penny Blake",
      "Kai Bartley",
      "Sydney Heron"
    ]
  },
  {
    "id": "the-vampire-diaries-characters",
    "title": "The Vampire Diaries Characters",
    "items": [
      "Elena Gilbert",
      "Stefan Salvatore",
      "Damon Salvatore",
      "Bonnie Bennett",
      "Caroline Forbes",
      "Matt Donovan",
      "Jeremy Gilbert",
      "Tyler Lockwood",
      "Alaric Saltzman",
      "Klaus Mikaelson",
      "Elijah Mikaelson",
      "Rebekah Mikaelson",
      "Kol Mikaelson",
      "Finn Mikaelson",
      "Mikael",
      "Esther Mikaelson",
      "Katherine Pierce",
      "Silas",
      "Amara",
      "Qetsiyah",
      "Enzo St. John",
      "Lily Salvatore",
      "Kai Parker",
      "Liv Parker",
      "Luke Parker",
      "Jo Laughlin",
      "Jenna Sommers",
      "John Gilbert",
      "Isobel Flemming",
      "Vicki Donovan",
      "Anna",
      "Pearl",
      "Mason Lockwood",
      "Rose",
      "Jules",
      "Hayley Marshall",
      "Nadia Petrova",
      "Shane",
      "Lexi Branson",
      "Valerie Tulle",
      "Nora Hildegard",
      "Mary Louise",
      "Julian",
      "Cade",
      "Sybil"
    ]
  },
  {
    "id": "tv-show-characters",
    "title": "Tv Show Characters",
    "items": [
      "Michael Scott",
      "Pam Beesly",
      "Jim Halpert",
      "Dwight Schrute",
      "Leslie Knope",
      "Ron Swanson",
      "April Ludgate",
      "Nick Miller",
      "Jess Day",
      "Schmidt",
      "Rachel Green",
      "Monica Geller",
      "Chandler Bing",
      "Phoebe Buffay",
      "Ross Geller",
      "Carrie Bradshaw",
      "Miranda Hobbes",
      "Samantha Jones",
      "Charlotte York",
      "Ted Mosby",
      "Barney Stinson",
      "Robin Scherbatsky",
      "Marshall Eriksen",
      "Lorelai Gilmore",
      "Rory Gilmore",
      "Blair Waldorf",
      "Serena van der Woodsen",
      "Walter White",
      "Jesse Pinkman",
      "Saul Goodman",
      "Don Draper",
      "Peggy Olson",
      "Tony Soprano",
      "Carmela Soprano",
      "Fleabag",
      "Villanelle",
      "Eve Polastri",
      "Eleven",
      "Dustin Henderson",
      "Rue Bennett",
      "Mabel Mora",
      "Tyrion Lannister",
      "Arya Stark",
      "Wednesday Addams",
      "Moe Szyslak"
    ]
  },
  {
    "id": "movie-characters",
    "title": "Movie Characters",
    "items": [
      "Indiana Jones",
      "Ellen Ripley",
      "Marty McFly",
      "Ferris Bueller",
      "Forrest Gump",
      "Rocky Balboa",
      "Sarah Connor",
      "The Terminator",
      "Clarice Starling",
      "Darth Vader",
      "Luke Skywalker",
      "Princess Leia",
      "Han Solo",
      "Hermione Granger",
      "Harry Potter",
      "Ron Weasley",
      "Katniss Everdeen",
      "Elle Woods",
      "Amélie Poulain",
      "Vito Corleone",
      "Michael Corleone",
      "Tony Montana",
      "Travis Bickle",
      "Tyler Durden",
      "The Bride",
      "Jules Winnfield",
      "Vincent Vega",
      "Willy Wonka",
      "Peter Venkman",
      "Marge Gunderson",
      "The Dude",
      "Woody",
      "Buzz Lightyear",
      "Shrek",
      "Princess Fiona",
      "Remy",
      "Anton Chigurh",
      "Mia Wallace",
      "Rick Blaine",
      "Ilsa Lund",
      "Juno MacGuff",
      "Cher Horowitz",
      "Andy Sachs",
      "Miranda Priestly",
      "Moana"
    ]
  },
  {
    "id": "authors",
    "title": "Authors",
    "items": [
      "Jane Austen",
      "Charles Dickens",
      "George Eliot",
      "Virginia Woolf",
      "James Joyce",
      "Toni Morrison",
      "Margaret Atwood",
      "Kazuo Ishiguro",
      "Salman Rushdie",
      "Donna Tartt",
      "C.S. Lewis",
      "J.R.R. Tolkien",
      "Harper Lee",
      "George Orwell",
      "Aldous Huxley",
      "F. Scott Fitzgerald",
      "Ernest Hemingway",
      "William Faulkner",
      "Emily Brontë",
      "Charlotte Brontë",
      "Anne Tyler",
      "Alice Munro",
      "Hilary Mantel",
      "Arundhati Roy",
      "Zadie Smith",
      "Ian McEwan",
      "Colson Whitehead",
      "Jhumpa Lahiri",
      "Michael Ondaatje",
      "Maya Angelou",
      "John Steinbeck",
      "Philip Roth",
      "Vladimir Nabokov",
      "Kurt Vonnegut",
      "Elena Ferrante",
      "John Irving",
      "Louise Erdrich",
      "Ann Patchett",
      "David Mitchell",
      "Chimamanda Ngozi Adichie",
      "Khaled Hosseini",
      "Stephen King",
      "Isabel Allende",
      "Oscar Wilde",
      "Rohinton Mistry"
    ]
  },
  {
    "id": "artists",
    "title": "Artists",
    "items": [
      "Pablo Picasso",
      "Vincent van Gogh",
      "Claude Monet",
      "Rembrandt",
      "Johannes Vermeer",
      "Edgar Degas",
      "Paul Cézanne",
      "Henri Matisse",
      "Wassily Kandinsky",
      "Jackson Pollock",
      "Georgia O'Keeffe",
      "Frida Kahlo",
      "Salvador Dalí",
      "Edvard Munch",
      "Pierre-Auguste Renoir",
      "Paul Klee",
      "Joan Miró",
      "Gustav Klimt",
      "Jan van Eyck",
      "Sandro Botticelli",
      "Michelangelo",
      "Raphael",
      "Titian",
      "El Greco",
      "Caravaggio",
      "Diego Velázquez",
      "Francisco Goya",
      "J.M.W. Turner",
      "John Constable",
      "Caspar David Friedrich",
      "Mary Cassatt",
      "Berthe Morisot",
      "Camille Pissarro",
      "Georges Seurat",
      "Amedeo Modigliani",
      "Marc Chagall",
      "Henri Rousseau",
      "Egon Schiele",
      "Piet Mondrian",
      "Willem de Kooning",
      "Edward Hopper",
      "Grant Wood",
      "Winslow Homer",
      "Thomas Eakins",
      "Lucian Freud"
    ]
  },
  {
    "id": "canadian-politicians",
    "title": "Canadian Politicians",
    "items": [
      "Justin Trudeau",
      "Pierre Trudeau",
      "John A. Macdonald",
      "Wilfrid Laurier",
      "Lester B. Pearson",
      "Brian Mulroney",
      "Jean Chrétien",
      "Paul Martin",
      "Stephen Harper",
      "Kim Campbell",
      "Joe Clark",
      "John Turner",
      "Alexander Mackenzie",
      "Louis St. Laurent",
      "Arthur Meighen",
      "R.B. Bennett",
      "William Lyon Mackenzie King",
      "Mackenzie Bowell",
      "Charles Tupper",
      "Robert Borden",
      "John Diefenbaker",
      "Tommy Douglas",
      "Jagmeet Singh",
      "Andrew Scheer",
      "Erin O'Toole",
      "Pierre Poilievre",
      "Chrystia Freeland",
      "Anita Anand",
      "Mélanie Joly",
      "Bill Morneau",
      "Stockwell Day",
      "Jack Layton",
      "Thomas Mulcair",
      "Rachel Notley",
      "Danielle Smith",
      "Kathleen Wynne",
      "Doug Ford",
      "David Eby",
      "Christy Clark",
      "Jason Kenney",
      "Naheed Nenshi",
      "Olivia Chow",
      "Hazel McCallion",
      "Preston Manning",
      "David Johnston"
    ]
  },
  {
    "id": "animators",
    "title": "Animators",
    "items": [
      "Walt Disney",
      "Chuck Jones",
      "Hayao Miyazaki",
      "Isao Takahata",
      "Glen Keane",
      "Genndy Tartakovsky",
      "Rebecca Sugar",
      "Don Bluth",
      "John Lasseter",
      "Brad Bird",
      "Pete Docter",
      "Jennifer Lee",
      "Chris Sanders",
      "Dean DeBlois",
      "Nick Park",
      "Andreas Deja",
      "Richard Williams",
      "Matt Groening",
      "Pendleton Ward",
      "Craig McCracken",
      "Lauren Faust",
      "Bruce Timm",
      "Mamoru Hosoda",
      "Satoshi Kon",
      "Makoto Shinkai",
      "Masaaki Yuasa",
      "Nina Paley",
      "Bill Plympton",
      "Stephen Hillenburg",
      "Butch Hartman",
      "Jorge Gutierrez",
      "Peter Chung",
      "Ralph Bakshi",
      "Lotte Reiniger",
      "Tex Avery",
      "Ub Iwerks",
      "Winsor McCay",
      "Osamu Tezuka",
      "Naoko Yamada",
      "Tomm Moore",
      "Nora Twomey",
      "Michel Ocelot",
      "Shannon Tindle",
      "Chris Wedge",
      "Gorō Miyazaki"
    ]
  },
  {
    "id": "song-titles",
    "title": "Song Titles",
    "items": [
      "Imagine",
      "Halo",
      "Firework",
      "Bad Guy",
      "Stay",
      "Uptown Funk",
      "Royals",
      "Poker Face",
      "Yellow",
      "Wonderwall",
      "Hey Jude",
      "Purple Rain",
      "Rolling in the Deep",
      "Single Ladies",
      "Shake It Off",
      "Levitating",
      "Viva La Vida",
      "Mr. Brightside",
      "Call Me Maybe",
      "Waterfalls",
      "Take on Me",
      "Dancing Queen",
      "Bohemian Rhapsody",
      "Toxic",
      "Since U Been Gone",
      "Teenage Dream",
      "Blinding Lights",
      "Umbrella",
      "Hello",
      "Dreams",
      "Africa",
      "Creep",
      "Landslide",
      "Jolene",
      "Fast Car",
      "I Will Survive",
      "Respect",
      "Crazy in Love",
      "Hound Dog",
      "Billie Jean",
      "Like a Prayer",
      "Material Girl",
      "As It Was",
      "Flowers",
      "Shallow"
    ]
  },
  {
    "id": "movie-titles",
    "title": "Movie Titles",
    "items": [
      "The Matrix",
      "Inception",
      "Titanic",
      "Avatar",
      "Gladiator",
      "Interstellar",
      "The Godfather",
      "Pulp Fiction",
      "The Dark Knight",
      "Forrest Gump",
      "Casablanca",
      "Jaws",
      "Alien",
      "Rocky",
      "Goodfellas",
      "The Departed",
      "Whiplash",
      "Arrival",
      "Barbie",
      "Oppenheimer",
      "La La Land",
      "Moonlight",
      "Parasite",
      "The Shawshank Redemption",
      "The Silence of the Lambs",
      "Jurassic Park",
      "Back to the Future",
      "The Truman Show",
      "No Country for Old Men",
      "There Will Be Blood",
      "Blade Runner",
      "Top Gun",
      "Toy Story",
      "Finding Nemo",
      "The Lion King",
      "Die Hard",
      "Get Out",
      "Her",
      "The Social Network",
      "Little Women",
      "A Few Good Men",
      "The Prestige",
      "Shrek",
      "Memento",
      "The Grand Budapest Hotel"
    ]
  },
  {
    "id": "book-titles",
    "title": "Book Titles",
    "items": [
      "1984",
      "A Farewell to Arms",
      "A Little Life",
      "A Tale of Two Cities",
      "A Wrinkle in Time",
      "Anne of Green Gables",
      "Beloved",
      "Brave New World",
      "Catch-22",
      "Charlotte's Web",
      "Crime and Punishment",
      "Dune",
      "Emma",
      "Fahrenheit 451",
      "Frankenstein",
      "Gone Girl",
      "Great Expectations",
      "Hamlet",
      "Jane Eyre",
      "Little Women",
      "Lolita",
      "Moby-Dick",
      "Normal People",
      "Of Mice and Men",
      "On the Road",
      "One Hundred Years of Solitude",
      "Persuasion",
      "Pride and Prejudice",
      "Rebecca",
      "Sense and Sensibility",
      "Slaughterhouse-Five",
      "The Bell Jar",
      "The Book Thief",
      "The Catcher in the Rye",
      "The Color Purple",
      "The Fellowship of the Ring",
      "The Giver",
      "The Goldfinch",
      "The Great Gatsby",
      "The Handmaid's Tale",
      "The Hobbit",
      "The Hunger Games",
      "The Kite Runner",
      "The Odyssey",
      "To Kill a Mockingbird"
    ]
  },
  {
    "id": "types-of-pasta",
    "title": "Types Of Pasta",
    "items": [
      "spaghetti",
      "penne",
      "rigatoni",
      "fusilli",
      "farfalle",
      "linguine",
      "fettuccine",
      "ravioli",
      "tortellini",
      "gnocchi",
      "ziti",
      "macaroni",
      "cavatappi",
      "rotini",
      "bucatini",
      "orecchiette",
      "pappardelle",
      "lasagna",
      "tagliatelle",
      "vermicelli",
      "angel hair",
      "ditalini",
      "manicotti",
      "capellini",
      "gemelli",
      "mafaldine",
      "radiatori",
      "campanelle",
      "strozzapreti",
      "paccheri",
      "anelletti",
      "bigoli",
      "casarecce",
      "trofie",
      "malloreddus",
      "lumache",
      "fregola",
      "mezzi rigatoni",
      "spaghettini",
      "cellentani",
      "tubetti",
      "sedani",
      "filini",
      "orzo",
      "cannelloni"
    ]
  },
  {
    "id": "types-of-coffee",
    "title": "Types Of Coffee",
    "items": [
      "americano",
      "affogato",
      "au lait",
      "breve",
      "café bombón",
      "café cubano",
      "café de olla",
      "café miel",
      "café mocha",
      "cappuccino",
      "cold brew",
      "cortado",
      "dalgona",
      "doppio",
      "espresso",
      "flat white",
      "frappé",
      "freddo espresso",
      "freddo cappuccino",
      "irish coffee",
      "latte",
      "lungo",
      "macchiato",
      "marocchino",
      "mazagran",
      "nitro cold brew",
      "piccolo",
      "red eye",
      "ristretto",
      "romano",
      "turkish coffee",
      "vienna coffee",
      "white coffee",
      "gibraltar",
      "iced latte",
      "iced americano",
      "iced mocha",
      "black coffee",
      "drip coffee",
      "pour-over",
      "french press",
      "aeropress",
      "chemex",
      "dirty chai",
      "bulletproof coffee"
    ]
  },
  {
    "id": "technology-items",
    "title": "Technology Items",
    "items": [
      "laptop",
      "desktop",
      "tablet",
      "smartphone",
      "keyboard",
      "mouse",
      "monitor",
      "printer",
      "router",
      "modem",
      "smartwatch",
      "earbuds",
      "headphones",
      "webcam",
      "microphone",
      "hard drive",
      "SSD",
      "USB cable",
      "charger",
      "power bank",
      "graphics card",
      "motherboard",
      "processor",
      "RAM",
      "flash drive",
      "drone",
      "VR headset",
      "projector",
      "streaming stick",
      "game console",
      "e-reader",
      "smart speaker",
      "fitness tracker",
      "Wi-Fi extender",
      "dock",
      "stylus",
      "tripod",
      "ring light",
      "NAS",
      "3D printer",
      "server rack",
      "switch",
      "mechanical keyboard",
      "mouse pad",
      "phone stand"
    ]
  },
  {
    "id": "trees",
    "title": "Trees",
    "items": [
      "oak",
      "maple",
      "pine",
      "spruce",
      "fir",
      "cedar",
      "birch",
      "elm",
      "ash",
      "willow",
      "poplar",
      "beech",
      "sycamore",
      "hemlock",
      "yew",
      "redwood",
      "sequoia",
      "larch",
      "alder",
      "cherry",
      "apple",
      "pear",
      "plum",
      "hawthorn",
      "holly",
      "juniper",
      "magnolia",
      "dogwood",
      "walnut",
      "chestnut",
      "hickory",
      "cypress",
      "eucalyptus",
      "baobab",
      "olive",
      "fig",
      "mulberry",
      "cottonwood",
      "rowan",
      "ginkgo",
      "acacia",
      "aspen",
      "hornbeam",
      "lime",
      "teak"
    ]
  },
  {
    "id": "plants",
    "title": "Plants",
    "items": [
      "aloe",
      "bamboo",
      "begonia",
      "calathea",
      "cactus",
      "camellia",
      "coleus",
      "croton",
      "dahlia",
      "dracaena",
      "fern",
      "fuchsia",
      "gardenia",
      "geranium",
      "hibiscus",
      "hosta",
      "hydrangea",
      "ivy",
      "jade plant",
      "jasmine",
      "lavender",
      "lilac",
      "marigold",
      "mint",
      "monstera",
      "orchid",
      "pansy",
      "peony",
      "petunia",
      "philodendron",
      "pothos",
      "primrose",
      "rosemary",
      "rubber plant",
      "sage",
      "snake plant",
      "spider plant",
      "sunflower",
      "thyme",
      "tulip",
      "venus flytrap",
      "wisteria",
      "yucca",
      "zinnia",
      "peace lily"
    ]
  },
  {
    "id": "spices-and-herbs",
    "title": "Spices And Herbs",
    "items": [
      "allspice",
      "anise",
      "basil",
      "bay leaf",
      "caraway",
      "cardamom",
      "cayenne",
      "celery seed",
      "chervil",
      "chili powder",
      "chives",
      "cilantro",
      "cinnamon",
      "clove",
      "coriander",
      "cumin",
      "curry powder",
      "dill",
      "fennel",
      "fenugreek",
      "garlic powder",
      "ginger",
      "lavender",
      "lemongrass",
      "marjoram",
      "mint",
      "mustard seed",
      "nutmeg",
      "oregano",
      "paprika",
      "parsley",
      "peppermint",
      "rosemary",
      "saffron",
      "sage",
      "savory",
      "sesame",
      "star anise",
      "sumac",
      "tarragon",
      "thyme",
      "turmeric",
      "vanilla",
      "za'atar",
      "lovage"
    ]
  },
  {
    "id": "colours",
    "title": "Colours",
    "items": [
      "red",
      "orange",
      "yellow",
      "green",
      "blue",
      "purple",
      "pink",
      "brown",
      "black",
      "white",
      "grey",
      "beige",
      "navy",
      "teal",
      "turquoise",
      "maroon",
      "burgundy",
      "lavender",
      "violet",
      "indigo",
      "magenta",
      "cyan",
      "mustard",
      "olive",
      "mint",
      "peach",
      "coral",
      "salmon",
      "ivory",
      "charcoal",
      "taupe",
      "tan",
      "khaki",
      "cream",
      "gold",
      "silver",
      "bronze",
      "plum",
      "lilac",
      "aqua",
      "amber",
      "scarlet",
      "crimson",
      "emerald",
      "sapphire"
    ]
  },
  {
    "id": "items-of-clothing",
    "title": "Items Of Clothing",
    "items": [
      "blazer",
      "cardigan",
      "coat",
      "dress",
      "hoodie",
      "jacket",
      "jeans",
      "jumper",
      "leggings",
      "parka",
      "raincoat",
      "shirt",
      "shorts",
      "skirt",
      "sweater",
      "t-shirt",
      "tank top",
      "trousers",
      "vest",
      "windbreaker",
      "anorak",
      "belt",
      "blouse",
      "bodysuit",
      "boots",
      "cap",
      "clogs",
      "corset",
      "flannel",
      "gloves",
      "hat",
      "mittens",
      "onesie",
      "pajamas",
      "poncho",
      "robe",
      "sandals",
      "scarf",
      "shawl",
      "slippers",
      "socks",
      "stockings",
      "suit",
      "sundress",
      "turtleneck"
    ]
  },
  {
    "id": "tech-companies",
    "title": "Tech Companies",
    "items": [
      "Apple",
      "Microsoft",
      "Google",
      "Amazon",
      "Meta",
      "Netflix",
      "Nvidia",
      "Intel",
      "AMD",
      "IBM",
      "Oracle",
      "Salesforce",
      "Adobe",
      "Cisco",
      "Qualcomm",
      "Samsung",
      "Sony",
      "LG",
      "Dell",
      "HP",
      "Lenovo",
      "Asus",
      "Acer",
      "Zoom",
      "Spotify",
      "Uber",
      "Airbnb",
      "PayPal",
      "Shopify",
      "Block",
      "Stripe",
      "OpenAI",
      "Palantir",
      "Snap",
      "Pinterest",
      "Reddit",
      "Dropbox",
      "Slack",
      "Canva",
      "Atlassian",
      "ServiceNow",
      "Snowflake",
      "Datadog",
      "Cloudflare",
      "Tesla"
    ]
  },
  {
    "id": "clothing-brands",
    "title": "Clothing Brands",
    "items": [
      "Nike",
      "Adidas",
      "Puma",
      "Reebok",
      "Levi's",
      "Gap",
      "Old Navy",
      "H&M",
      "Zara",
      "Uniqlo",
      "Aritzia",
      "Lululemon",
      "Patagonia",
      "The North Face",
      "Canada Goose",
      "Burberry",
      "Gucci",
      "Prada",
      "Chanel",
      "Dior",
      "Louis Vuitton",
      "Versace",
      "Balenciaga",
      "Valentino",
      "Coach",
      "Michael Kors",
      "Tommy Hilfiger",
      "Calvin Klein",
      "Ralph Lauren",
      "Guess",
      "Mango",
      "Banana Republic",
      "Abercrombie & Fitch",
      "Hollister",
      "American Eagle",
      "J.Crew",
      "Anthropologie",
      "Free People",
      "Everlane",
      "Madewell",
      "Vans",
      "Converse",
      "Dr. Martens",
      "Moncler",
      "Fendi"
    ]
  },
  {
    "id": "band-names",
    "title": "Band Names",
    "items": [
      "The Beatles",
      "The Rolling Stones",
      "Fleetwood Mac",
      "Led Zeppelin",
      "Pink Floyd",
      "Queen",
      "U2",
      "Coldplay",
      "Radiohead",
      "Nirvana",
      "Pearl Jam",
      "The Cure",
      "The Smiths",
      "Arctic Monkeys",
      "The Killers",
      "Imagine Dragons",
      "Maroon 5",
      "OneRepublic",
      "Linkin Park",
      "Green Day",
      "Blink-182",
      "Paramore",
      "No Doubt",
      "Destiny's Child",
      "The Supremes",
      "Earth, Wind & Fire",
      "The Beach Boys",
      "The Doors",
      "The Strokes",
      "The National",
      "The Cranberries",
      "ABBA",
      "BTS",
      "Blackpink",
      "The 1975",
      "Bon Jovi",
      "Journey",
      "Aerosmith",
      "Kiss",
      "R.E.M.",
      "The Police",
      "Talking Heads",
      "Foo Fighters",
      "Eagles",
      "Boyz II Men"
    ]
  },
  {
    "id": "words-starting-with-break",
    "title": "Words Starting With Break",
    "items": [
      "break apart",
      "break away",
      "break bad",
      "break bread",
      "break camp",
      "break cover",
      "break even",
      "break free",
      "break ground",
      "break in",
      "break loose",
      "break out",
      "break point",
      "break rank",
      "break silence",
      "break stride",
      "break the ice",
      "break the news",
      "break the record",
      "break through",
      "break up",
      "break wind",
      "break off",
      "break faith",
      "break formation",
      "break line",
      "break open",
      "break pattern",
      "break precedent",
      "break right",
      "break left",
      "break south",
      "break north",
      "break tradition",
      "breakwater",
      "breakfront",
      "breakdance",
      "breakbeat",
      "breakfall",
      "breakneck",
      "breakroom",
      "breaktime",
      "breakwall",
      "breakaway",
      "breakout"
    ]
  },
  {
    "id": "words-ending-with-light",
    "title": "Words Ending With Light",
    "items": [
      "candlelight",
      "daylight",
      "firelight",
      "flashlight",
      "floodlight",
      "gaslight",
      "greenlight",
      "headlight",
      "highlight",
      "limelight",
      "moonlight",
      "nightlight",
      "penlight",
      "pinlight",
      "ring light",
      "searchlight",
      "skylight",
      "spotlight",
      "sunlight",
      "taillight",
      "torchlight",
      "uplight",
      "backlight",
      "booklight",
      "lamplight",
      "starlight",
      "streetlight",
      "bluelight",
      "redlight",
      "lowlight",
      "downlight",
      "fairylight",
      "keylight",
      "filllight",
      "safelight",
      "beaconlight",
      "porchlight",
      "worklight",
      "pilotlight",
      "warning light",
      "brake light",
      "dome light",
      "map light",
      "footlight",
      "daylight saving light"
    ]
  },
  {
    "id": "canadian-cities",
    "title": "Canadian Cities",
    "items": [
      "Toronto",
      "Montreal",
      "Vancouver",
      "Calgary",
      "Edmonton",
      "Ottawa",
      "Winnipeg",
      "Quebec City",
      "Hamilton",
      "Kitchener",
      "London",
      "Victoria",
      "Halifax",
      "Oshawa",
      "Windsor",
      "Saskatoon",
      "Regina",
      "St. John's",
      "Barrie",
      "Kelowna",
      "Abbotsford",
      "Sudbury",
      "Kingston",
      "Trois-Rivières",
      "Guelph",
      "Thunder Bay",
      "Moncton",
      "Brantford",
      "Red Deer",
      "Lethbridge",
      "Kamloops",
      "Whitehorse",
      "Yellowknife",
      "Fredericton",
      "Charlottetown",
      "Nanaimo",
      "Sherbrooke",
      "Drummondville",
      "Chilliwack",
      "Peterborough",
      "Sarnia",
      "Medicine Hat",
      "Grande Prairie",
      "Moose Jaw",
      "Prince George"
    ]
  },
  {
    "id": "dog-breeds",
    "title": "Dog Breeds",
    "items": [
      "Akita",
      "Basenji",
      "Beagle",
      "Bernese Mountain Dog",
      "Bichon Frise",
      "Bloodhound",
      "Border Collie",
      "Boston Terrier",
      "Boxer",
      "Brittany",
      "Bull Terrier",
      "Bulldog",
      "Cairn Terrier",
      "Cane Corso",
      "Cavalier King Charles Spaniel",
      "Chihuahua",
      "Chow Chow",
      "Cocker Spaniel",
      "Collie",
      "Corgi",
      "Dachshund",
      "Dalmatian",
      "Doberman Pinscher",
      "English Setter",
      "French Bulldog",
      "German Shepherd",
      "German Shorthaired Pointer",
      "Golden Retriever",
      "Great Dane",
      "Greyhound",
      "Havanese",
      "Irish Setter",
      "Jack Russell Terrier",
      "Labrador Retriever",
      "Lhasa Apso",
      "Maltese",
      "Miniature Pinscher",
      "Newfoundland",
      "Old English Sheepdog",
      "Papillon",
      "Pekingese",
      "Pomeranian",
      "Poodle",
      "Pug",
      "Rottweiler"
    ]
  },
  {
    "id": "flowers",
    "title": "Flowers",
    "items": [
      "alyssum",
      "anemone",
      "aster",
      "azalea",
      "begonia",
      "bellflower",
      "black-eyed susan",
      "bluebell",
      "buttercup",
      "camellia",
      "carnation",
      "chrysanthemum",
      "clematis",
      "columbine",
      "coneflower",
      "cosmos",
      "crocus",
      "dahlia",
      "daisy",
      "delphinium",
      "foxglove",
      "freesia",
      "gardenia",
      "geranium",
      "gladiolus",
      "hibiscus",
      "hollyhock",
      "hydrangea",
      "iris",
      "jasmine",
      "lavender",
      "lilac",
      "lily",
      "magnolia",
      "marigold",
      "nasturtium",
      "orchid",
      "pansy",
      "peony",
      "petunia",
      "phlox",
      "poppy",
      "primrose",
      "ranunculus",
      "rose"
    ]
  },
  {
    "id": "sci-fi-shows",
    "title": "Sci-Fi Shows",
    "items": [
      "Andor",
      "Battlestar Galactica",
      "Black Mirror",
      "Doctor Who",
      "Fallout",
      "Firefly",
      "For All Mankind",
      "Foundation",
      "Fringe",
      "Futurama",
      "Humans",
      "Lost in Space",
      "Orphan Black",
      "Quantum Leap",
      "Raised by Wolves",
      "Red Dwarf",
      "Silo",
      "Star Trek",
      "Star Trek: Discovery",
      "Star Trek: Picard",
      "Star Trek: Strange New Worlds",
      "Star Wars: The Clone Wars",
      "Stargate Atlantis",
      "Stargate SG-1",
      "Stranger Things",
      "The 100",
      "The Expanse",
      "The Last of Us",
      "The Mandalorian",
      "The OA",
      "The Orville",
      "The Peripheral",
      "The Twilight Zone",
      "Torchwood",
      "Travelers",
      "Westworld",
      "Severance",
      "Snowpiercer",
      "Upload",
      "Terminator: The Sarah Connor Chronicles",
      "Counterpart",
      "Farscape",
      "Dark Matter",
      "The X-Files",
      "Continuum"
    ]
  },
  {
    "id": "comic-artists",
    "title": "Comic Artists",
    "items": [
      "Al Capp",
      "Alex Ross",
      "Art Spiegelman",
      "Bill Watterson",
      "Charles Addams",
      "Chris Ware",
      "Daniel Clowes",
      "David Mazzucchelli",
      "Frank Cho",
      "Frank Miller",
      "Gary Larson",
      "George Herriman",
      "Gil Kane",
      "Greg Capullo",
      "Jack Kirby",
      "Jaime Hernandez",
      "Jeff Smith",
      "Jim Davis",
      "Jim Lee",
      "Joe Kubert",
      "John Buscema",
      "John Byrne",
      "Lynn Johnston",
      "Marjane Satrapi",
      "Matt Groening",
      "Mike Mignola",
      "Moebius",
      "Neal Adams",
      "Osamu Tezuka",
      "P. Craig Russell",
      "Patrick McDonnell",
      "Quino",
      "Raina Telgemeier",
      "Rob Liefeld",
      "Robert Crumb",
      "Rumiko Takahashi",
      "Sergio Aragonés",
      "Stan Sakai",
      "Steve Ditko",
      "Terry Moore",
      "Todd McFarlane",
      "Walt Kelly",
      "Winsor McCay",
      "Will Eisner",
      "Lynda Barry"
    ]
  },
  {
    "id": "actor-names",
    "title": "Actor Names",
    "items": [
      "Amy Adams",
      "Andrew Garfield",
      "Anne Hathaway",
      "Bill Murray",
      "Brad Pitt",
      "Cate Blanchett",
      "Chris Evans",
      "Chris Hemsworth",
      "Christian Bale",
      "Daniel Craig",
      "Denzel Washington",
      "Emma Stone",
      "Emma Thompson",
      "Florence Pugh",
      "Gary Oldman",
      "Glenn Close",
      "Harrison Ford",
      "Idris Elba",
      "Jodie Foster",
      "Julia Roberts",
      "Julianne Moore",
      "Kate Winslet",
      "Keanu Reeves",
      "Kerry Washington",
      "Leonardo DiCaprio",
      "Lupita Nyong'o",
      "Mahershala Ali",
      "Margot Robbie",
      "Matt Damon",
      "Meryl Streep",
      "Michael B. Jordan",
      "Michelle Yeoh",
      "Natalie Portman",
      "Nicole Kidman",
      "Paul Mescal",
      "Pedro Pascal",
      "Rachel McAdams",
      "Regina King",
      "Ryan Gosling",
      "Saoirse Ronan",
      "Scarlett Johansson",
      "Sigourney Weaver",
      "Tom Cruise",
      "Tom Hanks",
      "Viola Davis"
    ]
  },
  {
    "id": "things-found-in-an-office",
    "title": "Things Found In An Office",
    "items": [
      "binder",
      "binder clip",
      "bookshelf",
      "briefcase",
      "bulletin board",
      "calculator",
      "calendar",
      "chair",
      "clipboard",
      "coffee mug",
      "computer mouse",
      "conference phone",
      "desk",
      "desk lamp",
      "drawer",
      "envelope",
      "eraser",
      "filing cabinet",
      "folder",
      "highlighter",
      "hole punch",
      "keyboard",
      "lanyard",
      "letter opener",
      "monitor",
      "notebook",
      "paper clips",
      "paper shredder",
      "pen",
      "pencil",
      "pencil cup",
      "planner",
      "printer",
      "projector",
      "pushpin",
      "recycling bin",
      "ruler",
      "scissors",
      "speakerphone",
      "stapler",
      "sticky notes",
      "surge protector",
      "tape dispenser",
      "telephone",
      "whiteboard"
    ]
  },
  {
    "id": "medical-dramas",
    "title": "Medical Dramas",
    "items": [
      "ER",
      "Grey's Anatomy",
      "House",
      "The Good Doctor",
      "St. Elsewhere",
      "Chicago Hope",
      "Private Practice",
      "Nurse Jackie",
      "Scrubs",
      "New Amsterdam",
      "Code Black",
      "The Resident",
      "Saving Hope",
      "Transplant",
      "Holby City",
      "Casualty",
      "Call the Midwife",
      "Doc Martin",
      "Mercy",
      "Hawthorne",
      "Three Rivers",
      "Strong Medicine",
      "Trauma",
      "Off the Map",
      "A Gifted Man",
      "Doogie Howser, M.D.",
      "Emily Owens, M.D.",
      "Pure Genius",
      "Nip/Tuck",
      "Body of Proof",
      "Royal Pains",
      "Getting On",
      "Medicine Ball",
      "Heartbeat",
      "The Knick",
      "SkyMed",
      "Bramwell",
      "Dr. Quinn, Medicine Woman",
      "The Night Shift",
      "Lenox Hill",
      "Critical",
      "Monday Mornings",
      "Diagnosis Murder",
      "Hospital Playlist",
      "MASH"
    ]
  },
  {
    "id": "sitcoms",
    "title": "Sitcoms",
    "items": [
      "Friends",
      "The Office",
      "Parks and Recreation",
      "Seinfeld",
      "Frasier",
      "Cheers",
      "Brooklyn Nine-Nine",
      "Modern Family",
      "New Girl",
      "Arrested Development",
      "Community",
      "30 Rock",
      "How I Met Your Mother",
      "Schitt's Creek",
      "Superstore",
      "Abbott Elementary",
      "The Good Place",
      "Black-ish",
      "The Nanny",
      "Will & Grace",
      "Scrubs",
      "Kim's Convenience",
      "Fresh Off the Boat",
      "Everybody Loves Raymond",
      "The Big Bang Theory",
      "That '70s Show",
      "Happy Endings",
      "Cougar Town",
      "Rules of Engagement",
      "Malcolm in the Middle",
      "The Middle",
      "Dharma & Greg",
      "Just Shoot Me!",
      "Wings",
      "Night Court",
      "NewsRadio",
      "Spin City",
      "2 Broke Girls",
      "Bob Hearts Abishola",
      "Reba",
      "Home Improvement",
      "Living Single",
      "Family Matters",
      "Full House",
      "Perfect Strangers"
    ]
  },
  {
    "id": "book-genres",
    "title": "Book Genres",
    "items": [
      "fantasy",
      "science fiction",
      "romance",
      "thriller",
      "mystery",
      "historical fiction",
      "literary fiction",
      "horror",
      "memoir",
      "biography",
      "autobiography",
      "poetry",
      "essay",
      "drama",
      "satire",
      "dystopian",
      "young adult",
      "middle grade",
      "graphic novel",
      "crime",
      "adventure",
      "western",
      "paranormal",
      "speculative fiction",
      "urban fantasy",
      "magical realism",
      "true crime",
      "self-help",
      "cookbook",
      "travel writing",
      "philosophy",
      "humour",
      "sports writing",
      "war fiction",
      "gothic fiction",
      "epistolary",
      "bildungsroman",
      "short story",
      "fairy tale",
      "mythology",
      "tragedy",
      "comedy",
      "detective fiction",
      "cyberpunk",
      "alternate history"
    ]
  },
  {
    "id": "pizza-toppings",
    "title": "Pizza Toppings",
    "items": [
      "pepperoni",
      "mushrooms",
      "sausage",
      "bacon",
      "ham",
      "pineapple",
      "green peppers",
      "onions",
      "olives",
      "extra cheese",
      "spinach",
      "tomatoes",
      "anchovies",
      "artichokes",
      "jalapeños",
      "banana peppers",
      "basil",
      "garlic",
      "broccoli",
      "chicken",
      "ground beef",
      "meatballs",
      "salami",
      "prosciutto",
      "ricotta",
      "feta",
      "goat cheese",
      "parmesan",
      "mozzarella",
      "cheddar",
      "sun-dried tomatoes",
      "roasted red peppers",
      "eggplant",
      "zucchini",
      "arugula",
      "pesto",
      "pepperoncini",
      "capers",
      "shrimp",
      "tuna",
      "corn",
      "pickles",
      "hot honey",
      "truffle oil",
      "fresh oregano"
    ]
  },
  {
    "id": "ice-cream-flavours",
    "title": "Ice Cream Flavours",
    "items": [
      "vanilla",
      "chocolate",
      "strawberry",
      "mint chocolate chip",
      "cookies and cream",
      "rocky road",
      "butter pecan",
      "coffee",
      "pistachio",
      "cookie dough",
      "birthday cake",
      "salted caramel",
      "moose tracks",
      "neapolitan",
      "french vanilla",
      "cherry",
      "black raspberry",
      "maple walnut",
      "mango",
      "coconut",
      "banana",
      "peanut butter",
      "rum raisin",
      "bubble gum",
      "cotton candy",
      "lemon",
      "green tea",
      "matcha",
      "tiramisu",
      "hazelnut",
      "toffee",
      "caramel swirl",
      "fudge brownie",
      "raspberry ripple",
      "blueberry",
      "peach",
      "pumpkin",
      "red velvet",
      "cheesecake",
      "s'mores",
      "dulce de leche",
      "ube",
      "black sesame",
      "cinnamon",
      "marshmallow"
    ]
  },
  {
    "id": "board-games",
    "title": "Board Games",
    "items": [
      "Monopoly",
      "Scrabble",
      "Risk",
      "Clue",
      "Catan",
      "Ticket to Ride",
      "Carcassonne",
      "Pandemic",
      "Azul",
      "Splendor",
      "Chess",
      "Checkers",
      "Backgammon",
      "Sorry!",
      "Life",
      "Yahtzee",
      "Boggle",
      "Battleship",
      "Connect 4",
      "Operation",
      "Guess Who?",
      "Jenga",
      "Twister",
      "Sequence",
      "Dominion",
      "Patchwork",
      "Codenames",
      "Dixit",
      "Hive",
      "Qwirkle",
      "Santorini",
      "7 Wonders",
      "Agricola",
      "Terra Mystica",
      "Wingspan",
      "Scythe",
      "Gloomhaven",
      "Cranium",
      "Pictionary",
      "Taboo",
      "Trivial Pursuit",
      "Mancala",
      "Go",
      "Othello",
      "Mouse Trap"
    ]
  },
  {
    "id": "sea-creatures",
    "title": "Sea Creatures",
    "items": [
      "shark",
      "whale",
      "dolphin",
      "octopus",
      "squid",
      "jellyfish",
      "lobster",
      "crab",
      "shrimp",
      "seahorse",
      "starfish",
      "clam",
      "oyster",
      "mussel",
      "seal",
      "walrus",
      "manatee",
      "narwhal",
      "eel",
      "stingray",
      "orca",
      "beluga",
      "sea lion",
      "swordfish",
      "marlin",
      "tuna",
      "cod",
      "salmon",
      "pufferfish",
      "anglerfish",
      "hammerhead",
      "krill",
      "plankton",
      "sea urchin",
      "sea cucumber",
      "coral",
      "anemone",
      "manta ray",
      "barracuda",
      "sardine",
      "herring",
      "halibut",
      "flounder",
      "grouper",
      "parrotfish"
    ]
  },
  {
    "id": "gemstones",
    "title": "Gemstones",
    "items": [
      "diamond",
      "ruby",
      "sapphire",
      "emerald",
      "amethyst",
      "topaz",
      "opal",
      "garnet",
      "peridot",
      "aquamarine",
      "tourmaline",
      "citrine",
      "onyx",
      "jade",
      "turquoise",
      "lapis lazuli",
      "moonstone",
      "sunstone",
      "zircon",
      "spinel",
      "tanzanite",
      "iolite",
      "alexandrite",
      "malachite",
      "agate",
      "carnelian",
      "jasper",
      "obsidian",
      "bloodstone",
      "fluorite",
      "amber",
      "coral",
      "pearl",
      "jet",
      "aventurine",
      "chrysoprase",
      "larimar",
      "unakite",
      "serpentine",
      "rhodonite",
      "sodalite",
      "charoite",
      "amazonite",
      "hematite",
      "pyrite"
    ]
  },
  {
    "id": "constellations",
    "title": "Constellations",
    "items": [
      "Orion",
      "Ursa Major",
      "Ursa Minor",
      "Cassiopeia",
      "Andromeda",
      "Pegasus",
      "Cygnus",
      "Lyra",
      "Aquila",
      "Taurus",
      "Gemini",
      "Cancer",
      "Leo",
      "Virgo",
      "Libra",
      "Scorpius",
      "Sagittarius",
      "Capricornus",
      "Aquarius",
      "Pisces",
      "Aries",
      "Draco",
      "Phoenix",
      "Hydra",
      "Centaurus",
      "Crux",
      "Carina",
      "Vela",
      "Puppis",
      "Perseus",
      "Auriga",
      "Boötes",
      "Canis Major",
      "Canis Minor",
      "Cepheus",
      "Delphinus",
      "Hercules",
      "Lepus",
      "Lupus",
      "Monoceros",
      "Musca",
      "Pavo",
      "Reticulum",
      "Triangulum",
      "Volans"
    ]
  },
  {
    "id": "composers",
    "title": "Composers",
    "items": [
      "Johann Sebastian Bach",
      "Ludwig van Beethoven",
      "Wolfgang Amadeus Mozart",
      "Franz Schubert",
      "Johannes Brahms",
      "Pyotr Ilyich Tchaikovsky",
      "Richard Wagner",
      "Giuseppe Verdi",
      "Antonio Vivaldi",
      "George Frideric Handel",
      "Joseph Haydn",
      "Felix Mendelssohn",
      "Robert Schumann",
      "Frédéric Chopin",
      "Franz Liszt",
      "Claude Debussy",
      "Maurice Ravel",
      "Igor Stravinsky",
      "Sergei Rachmaninoff",
      "Dmitri Shostakovich",
      "Sergei Prokofiev",
      "Gustav Mahler",
      "Antonín Dvořák",
      "Bedřich Smetana",
      "Jean Sibelius",
      "Edvard Grieg",
      "Camille Saint-Saëns",
      "Hector Berlioz",
      "Béla Bartók",
      "Anton Bruckner",
      "Giacomo Puccini",
      "Gaetano Donizetti",
      "Gioachino Rossini",
      "Vincenzo Bellini",
      "Aaron Copland",
      "Leonard Bernstein",
      "George Gershwin",
      "Philip Glass",
      "Steve Reich",
      "John Adams",
      "Arvo Pärt",
      "Olivier Messiaen",
      "Nikolai Rimsky-Korsakov",
      "Benjamin Britten",
      "Edward Elgar"
    ]
  },
  {
    "id": "car-brands",
    "title": "Car Brands",
    "items": [
      "Toyota",
      "Honda",
      "Ford",
      "Chevrolet",
      "Nissan",
      "BMW",
      "Mercedes-Benz",
      "Audi",
      "Volkswagen",
      "Hyundai",
      "Kia",
      "Mazda",
      "Subaru",
      "Lexus",
      "Acura",
      "Volvo",
      "Porsche",
      "Ferrari",
      "Lamborghini",
      "Maserati",
      "Bentley",
      "Rolls-Royce",
      "Jaguar",
      "Land Rover",
      "Jeep",
      "Dodge",
      "Chrysler",
      "Buick",
      "GMC",
      "Cadillac",
      "Infiniti",
      "Mini",
      "Mitsubishi",
      "Suzuki",
      "Peugeot",
      "Renault",
      "Fiat",
      "Alfa Romeo",
      "Škoda",
      "SEAT",
      "Citroën",
      "Tesla",
      "Rivian",
      "Lucid",
      "Genesis"
    ]
  },
  {
    "id": "cereals",
    "title": "Cereals",
    "items": [
      "Cheerios",
      "Corn Flakes",
      "Rice Krispies",
      "Froot Loops",
      "Frosted Flakes",
      "Lucky Charms",
      "Special K",
      "Cocoa Puffs",
      "Trix",
      "Cap'n Crunch",
      "Raisin Bran",
      "Mini-Wheats",
      "Honey Nut Cheerios",
      "Apple Jacks",
      "Cinnamon Toast Crunch",
      "Golden Grahams",
      "Honey Bunches of Oats",
      "Kix",
      "Chex",
      "Cocoa Krispies",
      "Count Chocula",
      "Cookie Crisp",
      "Wheaties",
      "Grape-Nuts",
      "Life",
      "Shredded Wheat",
      "Total",
      "Fruity Pebbles",
      "Cocoa Pebbles",
      "Corn Pops",
      "Cracklin' Oat Bran",
      "Basic 4",
      "Mueslix",
      "Alpha-Bits",
      "Vector",
      "All-Bran",
      "Bran Flakes",
      "Honeycomb",
      "Smart Start",
      "French Toast Crunch",
      "Krave",
      "Berry Berry Kix",
      "Golden Crisp",
      "Malt-O-Meal",
      "Product 19"
    ]
  },
  {
    "id": "candies",
    "title": "Candies",
    "items": [
      "Skittles",
      "Starburst",
      "M&M's",
      "Smarties",
      "Jolly Rancher",
      "Twizzlers",
      "Sour Patch Kids",
      "Swedish Fish",
      "Nerds",
      "Kit Kat",
      "Snickers",
      "Mars",
      "Milky Way",
      "Crunch",
      "Butterfinger",
      "Heath",
      "PayDay",
      "Rolo",
      "Tootsie Roll",
      "Milk Duds",
      "Junior Mints",
      "York Peppermint Pattie",
      "Reese's Pieces",
      "Reese's Peanut Butter Cups",
      "Twix",
      "Whoppers",
      "Airheads",
      "Laffy Taffy",
      "Runts",
      "Gobstopper",
      "Lemonhead",
      "Warheads",
      "Mike and Ike",
      "Dots",
      "Hot Tamales",
      "Red Hots",
      "Jelly Belly",
      "Haribo Goldbears",
      "Almond Joy",
      "Mounds",
      "Charleston Chew",
      "Bit-O-Honey",
      "Werther's Original",
      "Lifesavers",
      "Ring Pop"
    ]
  },
  {
    "id": "kitchen-tools",
    "title": "Kitchen Tools",
    "items": [
      "whisk",
      "spatula",
      "ladle",
      "tongs",
      "colander",
      "grater",
      "peeler",
      "can opener",
      "measuring cup",
      "measuring spoon",
      "cutting board",
      "chef's knife",
      "paring knife",
      "bread knife",
      "rolling pin",
      "mixing bowl",
      "skillet",
      "saucepan",
      "stockpot",
      "sheet pan",
      "baking dish",
      "muffin tin",
      "loaf pan",
      "cooling rack",
      "zester",
      "garlic press",
      "slotted spoon",
      "turner",
      "bench scraper",
      "mortar and pestle",
      "strainer",
      "salad spinner",
      "kettle",
      "toaster",
      "blender",
      "food processor",
      "immersion blender",
      "timer",
      "thermometer",
      "pizza cutter",
      "pastry brush",
      "cookie scoop",
      "melon baller",
      "mandoline",
      "sifter"
    ]
  },
  {
    "id": "garden-tools",
    "title": "Garden Tools",
    "items": [
      "shovel",
      "spade",
      "rake",
      "hoe",
      "trowel",
      "pruning shears",
      "loppers",
      "garden fork",
      "watering can",
      "hose",
      "sprinkler",
      "wheelbarrow",
      "leaf blower",
      "hedge trimmer",
      "lawn mower",
      "weed puller",
      "dibber",
      "hand cultivator",
      "soil scoop",
      "seed spreader",
      "garden gloves",
      "kneeling pad",
      "compost bin",
      "wheel hoe",
      "pickaxe",
      "mattock",
      "bulb planter",
      "edger",
      "pitchfork",
      "hand rake",
      "soil knife",
      "rain gauge",
      "plant ties",
      "twine",
      "watering wand",
      "hose reel",
      "potting bench",
      "garden cart",
      "pruning saw",
      "grass shears",
      "soil tester",
      "mulch fork",
      "transplanter",
      "aerator",
      "sprayer"
    ]
  }
];
